/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "xfoaiiykefuavjcdojxm"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inhmb2FpaXlrZWZ1YXZqY2RvanhtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzEyODIxNjcsImV4cCI6MjA4Njg1ODE2N30.lHB9_pP70chcbHlwxycMnuDqWPWYT16BQ-I_JoEX-q8"